"""task storage provider

Revision ID: a91b8183909c
Revises: 8dac4a5be0c0
Create Date: 2026-03-17 15:50:57.982220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91b8183909c'
down_revision: Union[str, Sequence[str], None] = '8dac4a5be0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('storage_provider', sa.String(), nullable=True))
    op.execute("UPDATE tasks SET storage_provider = 's3' WHERE storage_provider IS NULL")
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.alter_column('storage_provider', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('storage_provider')

    # ### end Alembic commands ###
