"""unique book filename

Revision ID: dc26ed64d18d
Revises: 804e2af768be
Create Date: 2026-04-29 19:53:07.105269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc26ed64d18d'
down_revision: Union[str, Sequence[str], None] = '804e2af768be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_books_filename", ['filename'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint("uq_books_filename", type_='unique')

    # ### end Alembic commands ###
